packages:
  - apps/*
  - packages/*
catalog:
  dotenv: ^17.2.2
  zod: ^4.1.13
  "@trpc/server": ^11.7.2
  better-auth: ^1.4.9
  "@types/express": ^5.0.1
  "@trpc/client": ^11.7.2
  "@libsql/client": 0.15.15
  libsql: 0.5.22
  "@types/react-dom": ^19.2.3
  tailwindcss: ^4.1.18
  drizzle-orm: ^0.45.1
