packages:
  - apps/*
  - packages/*

catalog:
  '@libsql/client': 0.15.15
  '@trpc/client': ^11.7.2
  '@trpc/server': ^11.7.2
  '@types/express': ^5.0.1
  '@types/react-dom': ^19.2.3
  better-auth: ^1.4.9
  dotenv: ^17.2.2
  drizzle-orm: ^0.45.1
  libsql: 0.5.22
  tailwindcss: ^4.1.18
  zod: ^4.1.13

onlyBuiltDependencies:
  - esbuild
  - msw
  - sharp
